// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PTLC.Data
{
    [Table("DeliveryStatus")]
    public partial class DeliveryStatus
    {
        public DeliveryStatus()
        {
            DeliveryItems = new HashSet<DeliveryItem>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string StatusName { get; set; }

        [InverseProperty(nameof(DeliveryItem.DeliveryStatusNavigation))]
        public virtual ICollection<DeliveryItem> DeliveryItems { get; set; }
    }
}