// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PTLC.Data
{
    public partial class DeliveryAddition
    {
        [Key]
        public int Id { get; set; }
        public string AdditionalName { get; set; }
        [Column(TypeName = "money")]
        public decimal? Rate { get; set; }
    }
}