// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PTLC.Data
{
    [Table("Merchant")]
    public partial class Merchant
    {
        public Merchant()
        {
            DeliveryMasters = new HashSet<DeliveryMaster>();
            RateMatrices = new HashSet<RateMatrix>();
        }

        [Key]
        public Guid Id { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string BusinessName { get; set; }
        public int? BusinessClass { get; set; }
        public string ContactPerson { get; set; }
        [StringLength(50)]
        public string TelNo { get; set; }
        [StringLength(50)]
        public string MobileNo { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Birthdate { get; set; }
        [StringLength(128)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(128)]
        public string UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        [StringLength(10)]
        public string Status { get; set; }
        public int? LogId { get; set; }
        public Guid? AgentId { get; set; }
        [Column(TypeName = "text")]
        public string Pic { get; set; }
        [StringLength(50)]
        public string QrCode { get; set; }

        [ForeignKey(nameof(AgentId))]
        [InverseProperty(nameof(SalesAgent.Merchants))]
        public virtual SalesAgent Agent { get; set; }
        [InverseProperty(nameof(DeliveryMaster.Merchant))]
        public virtual ICollection<DeliveryMaster> DeliveryMasters { get; set; }
        [InverseProperty(nameof(RateMatrix.Merchant))]
        public virtual ICollection<RateMatrix> RateMatrices { get; set; }
    }
}