// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PTLC.Data
{
    [Table("RateMatrix")]
    public partial class RateMatrix
    {
        [Key]
        public Guid MerchantId { get; set; }
        [Key]
        public int VehicleTypeId { get; set; }
        [Column(TypeName = "money")]
        public decimal? BaseRate { get; set; }
        [Column(TypeName = "money")]
        public decimal? KmRate { get; set; }
        [StringLength(128)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(128)]
        public string UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }

        [ForeignKey(nameof(MerchantId))]
        [InverseProperty("RateMatrices")]
        public virtual Merchant Merchant { get; set; }
        [ForeignKey(nameof(VehicleTypeId))]
        [InverseProperty("RateMatrices")]
        public virtual VehicleType VehicleType { get; set; }
    }
}