// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PTLC.Data
{
    [Table("SalesAgent")]
    public partial class SalesAgent
    {
        public SalesAgent()
        {
            Merchants = new HashSet<Merchant>();
        }

        [Key]
        public Guid Id { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string LastName { get; set; }
        public int? Age { get; set; }
        [Column(TypeName = "text")]
        public string Address { get; set; }
        [StringLength(50)]
        public string MobilePhone { get; set; }
        [StringLength(10)]
        public string Gender { get; set; }
        public string EmergencyContactPerson { get; set; }
        [Column(TypeName = "text")]
        public string EmergencyContactAddress { get; set; }
        [StringLength(50)]
        public string EmergencyContactMobilePhone { get; set; }
        [StringLength(50)]
        public string QrCode { get; set; }
        [Column(TypeName = "text")]
        public string Photo { get; set; }

        [InverseProperty(nameof(Merchant.Agent))]
        public virtual ICollection<Merchant> Merchants { get; set; }
    }
}