// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PTLC.Data
{
    public partial class Vehicle
    {
        public Vehicle()
        {
            InspectionNotes = new HashSet<InspectionNote>();
        }

        [Key]
        public string LicenseNumber { get; set; }
        [Required]
        public string Make { get; set; }
        [Required]
        public string Model { get; set; }
        public DateTime RegistrationDate { get; set; }
        public int Mileage { get; set; }
        public int Tank { get; set; }
        public DateTime LastUpdated { get; set; }

        [InverseProperty(nameof(InspectionNote.VehicleLicenseNumberNavigation))]
        public virtual ICollection<InspectionNote> InspectionNotes { get; set; }
    }
}