// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PTLC.Data
{
    [Table("VehicleType")]
    public partial class VehicleType
    {
        [Key]
        public int Id { get; set; }
        public string VehicleName { get; set; }
        public string Capacity { get; set; }

        [InverseProperty("VehicleType")]
        public virtual RateMatrix RateMatrix { get; set; }
    }
}